### ISSUE TITLE
Bug with informative error message

### ISSUE THREAD

**Issue by esheldon** [esheldon/gmix_meds#6]
I got this error below @beckermr .  It looks like the error is no cutout found, but the bug is that you are trying to format icut_obj, which is an array, as an integer

```
Traceback (most recent call last):
  File "/astro/u/esheldon/exports/gmix_meds-local/bin/gmix-fit-meds", line 601, in <module>
    main()
  File "/astro/u/esheldon/exports/gmix_meds-local/bin/gmix-fit-meds", line 599, in main
    go(config_file, meds_files, out_file, options)
  File "/astro/u/esheldon/exports/gmix_meds-local/bin/gmix-fit-meds", line 576, in go
    checkpoint_data=checkpoint_data)
  File "/astro/u/esheldon/exports/gmix_meds-local/bin/gmix-fit-meds", line 488, in run_fitter
    checkpoint_data=checkpoint_data)
  File "/astro/u/esheldon/exports/gmix_meds-local/bin/gmix-fit-meds", line 259, in run_ngmix
    gm.do_fits()
  File "/astro/u/esheldon/exports/gmix_meds-local/lib/python2.7/site-packages/gmix_meds/nfit.py", line 285, in do_fits
    self.fit_obj(dindex)
  File "/astro/u/esheldon/exports/gmix_meds-local/lib/python2.7/site-packages/gmix_meds/nfit.py", line 331, in fit_obj
    self._get_multi_band_observations(mindex)
  File "/astro/u/esheldon/exports/gmix_meds-local/lib/python2.7/site-packages/gmix_meds/nfit.py", line 578, in _get_multi_band_observations
    self._model_neighbors(mb_obs_list)
  File "/astro/u/esheldon/exports/gmix_meds-local/lib/python2.7/site-packages/gmix_meds/nfit.py", line 631, in _model_neighbors
    print("                could not find cutout for nbr %d cutout %d" % (cid,icut_obj))
```

**Comment by beckermr** [comment]
Closing this since it has been fixed.
